feat: add event specifications
openmeterio/openmeter pull request #1249
Opened 2024-07-24 14:45 UTC by turip

## Overview

This patch adds the ingestion and entitlement-based event signatures.

For usage please see the testcase for the parser. Right now we are only validating the balance
snapshot events, but it's possible to do it for other events if needed.

2024-07-25 08:42 UTC, turip commented on internal/event/types/event_type.go
> +func (s *EventTypeSpec) FillEvent(ev event.Event) {
Move to NewCloudEvent

2024-07-25 08:42 UTC, turip commented on internal/event/types/event_type.go
> +	if c.Time.IsZero() {
Move to NewCloudEvent

2024-07-25 09:11 UTC, chrisgacsal requested changes

2024-07-25 09:11 UTC, turip commented on internal/event/types/parser.go
> +	// Mandatory cloud events fields
Expected source/subject fields:

```
grant:
    source: //openmeter.io/namespace/<>/entitlement/<>/grant/<id>
    subject: //openmeter.io/namespace/<>/subject/<subjectID>

entitlement:
    source: //openmeter.io/namespace/<>/entitlement/<>
    subject: //openmeter.io/namespace/<>/subject/<subjectID>

ingest:
    source: //openmeter.io/namespace/<>/event
    subject: //openmeter.io/namespace/<>/subject/<subjectID>
```

2024-07-25 10:16 UTC, turip commented on internal/event/schema/entitlement_balance_snapshot.go
> +	EntitlementID string          `json:"entitlementId"`
I haven't expanded the subject, as it's a bit tricky in terms of cloud vs openmeter, others are done.

2024-07-26 08:08 UTC, chrisgacsal commented on internal/credit/events.go
> +var grantCreatedEventSpec = spec.EventTypeSpec{
```suggestion
var grantCreatedEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/credit/events.go
> +var grantVoidedEventSpec = spec.EventTypeSpec{
```suggestion
var grantVoidedEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/entitlement/events.go
> +var entitlementCreatedEventSpec = spec.EventTypeSpec{
```suggestion
var entitlementCreatedEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/entitlement/events.go
> +var entitlementDeletedEventSpec = spec.EventTypeSpec{
```suggestion
var entitlementDeletedEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/entitlement/metered/events.go
> +var resetEntitlementEventSpec = spec.EventTypeSpec{
```suggestion
var resetEntitlementEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/entitlement/snapshot/event.go
> +var entitlementBalanceSnapshotEventSpec = spec.EventTypeSpec{
```suggestion
var entitlementBalanceSnapshotEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/sink/events.go
> +var ingestEventSpec = spec.EventTypeSpec{
```suggestion
var ingestEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:08 UTC, chrisgacsal commented on internal/entitlement/metered/events.go
> +var createMeteredEntitlementGrantEventSpec = spec.EventTypeSpec{
```suggestion
var createMeteredEntitlementGrantEventSpec = spec.EventTypeSpec {
```

2024-07-26 08:21 UTC, chrisgacsal approved these changes

2024-07-26 08:25 UTC, merged