feat(customer): app api
openmeterio/openmeter pull request #1917
Opened 2024-11-25 20:33 UTC by hekike

Add apps support to customer to read and edit app specific metadata for the customer.

2024-11-25 23:51 UTC, hekike commented on openmeter/customer/adapter/customer.go
> +				WithApps(func(acq *entdb.AppCustomerQuery) {
The alternative would be to call app service, which would lead to waterfall DB queries and circular dependencies.

2024-11-26 13:28 UTC, tothandras requested changes

2024-11-26 13:28 UTC, tothandras commented on openmeter/app/stripe/observer/customer.go
> +			apps = append(apps, customerApp)
Do we need to append here?

2024-12-02 12:13 UTC, closed without merging

2024-12-02 12:13 UTC, hekike commented
Closing in favor of https://github.com/openmeterio/openmeter/pull/1919