feat(meter): query with accept csv support
openmeterio/openmeter pull request #260
Opened 2023-09-12 23:34 UTC by hekike

Accept CSV:

`curl --header "Accept: text/csv" http://localhost:8888/api/v1/meters/m1/query\?windowSize\=HOUR\&subject\=customer-1\&groupBy\=method\&groupBy\=path`

```
window_start,window_end,subject,method,path,value
2023-01-01T00:00:00Z,2023-01-01T01:00:00Z,customer-1,GET,/hello,2.000000
2023-01-02T00:00:00Z,2023-01-02T01:00:00Z,customer-1,GET,/hello,1.000000
```

2023-09-12 23:47 UTC, sagikazarmark requested changes
I would probably add a test to see how everything behaves when there is no subject in the response (subject is null).

2023-09-12 23:47 UTC, sagikazarmark commented on internal/server/router/router.go
> +	w.Write([]byte(csvContent))
How about using encoding/csv instead?

https://pkg.go.dev/encoding/csv

2023-09-12 23:47 UTC, sagikazarmark commented on internal/server/router/router.go
> +	if r.Header.Get("Accept") == "text/csv" {
Parsing media type would be safer: https://pkg.go.dev/mime#ParseMediaType

2023-09-12 23:47 UTC, sagikazarmark commented on internal/server/router/router.go
> +	if r.Header.Get("Accept") == "text/csv" {
Or use a snippet from the render library: https://github.com/go-chi/render/blob/v1.0.3/content_type.go#L67

(We should probably contribute CSV support to that library)

2023-09-13 09:10 UTC, tothandras approved these changes

2023-09-13 13:21 UTC, hekike commented on internal/server/router/router.go
> +	w.Write([]byte(csvContent))
Done

2023-09-13 13:24 UTC, merged