fix(seed): seed random int generators
openmeterio/openmeter pull request #264
Opened 2023-09-14 21:55 UTC by tothandras

2023-09-14 22:24 UTC, hekike approved these changes

2023-09-15 18:51 UTC, sagikazarmark requested changes

2023-09-15 18:51 UTC, sagikazarmark commented on etc/seed/seed.yaml
> +      let duration = random_int(seed:timestamp_unix_nano()) % 1000
```suggestion
      let duration = random_int(seed: timestamp_unix_nano(), max: 1000)
```

The problem is only with calculated values.

2023-09-30 11:52 UTC, sagikazarmark approved these changes

2023-09-30 11:52 UTC, merged