License
openmeterio/openmeter pull request #34
Opened 2023-06-12 16:13 UTC by KunalSin9h

## Overview

Fixes #22 

## Notes for reviewer

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-06-12 21:12 UTC, sagikazarmark requested changes
Good work, thanks @KunalSin9h! Can you please take a look at that one change request? Thanks!

2023-06-12 21:12 UTC, sagikazarmark commented on .licensei.toml
> +ignorePaths = ["vendor", "client", ".gen"]
```suggestion
ignorePaths = [".devenv", ".direnv", "vendor", "client", ".gen"]
```

2023-06-13 12:38 UTC, KunalSin9h commented
@sagikazarmark can you help here, it is failing in the license-check CI, saying `licensi` not found!

2023-06-16 15:53 UTC, KunalSin9h commented
i think after editing `flake.nix` i have not updated the `flake.lock` file, this might be a problem for this.

2023-06-21 23:34 UTC, sagikazarmark commented
@KunalSin9h I added licensei for you in #74

Please rebase this branch instead of merging main into it.

2023-06-22 05:58 UTC, closed without merging

2023-06-22 05:59 UTC, KunalSin9h commented
i think i have to create a new branch for this.