feat(quickstart): use unified meters
openmeterio/openmeter pull request #652
Opened 2024-03-02 17:12 UTC by hekike

Update quickstart and example meters to follow common meters:
https://openmeter.io/docs/getting-started/meter-examples

2024-03-03 19:07 UTC, sagikazarmark requested changes
Could you update other examples (collectors) as well?

2024-03-04 19:35 UTC, hekike commented
@sagikazarmark I created a separate issue about updating examples: https://github.com/openmeterio/openmeter/issues/657

2024-03-04 19:43 UTC, sagikazarmark commented
Please make sure to squash commits (that merge commit triggers me)

2024-03-04 19:43 UTC, sagikazarmark approved these changes

2024-03-04 19:56 UTC, merged